### ISSUE TITLE
doesnt work on my device

### ISSUE THREAD

**Issue by Pokem0n2** [kinopio-club/kinopio-client#529]
d:\kinopio-client>hostile set localhost kinopio.local
Added kinopio.local

d:\kinopio-client>npm run serve

> kinopio-client@1.0.0 serve d:\kinopio-client
> vite --host

(node:37412) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token '??='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:37412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:37412) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

d:\kinopio-client>node -v
v14.17.5

d:\kinopio-client>npm -v
6.14.14

**Comment by pketh** [comment]
Sounds like your node version is too low. Try ‘nvm use 20’. The min versions are specified in package.json. Wonder if there’s a way to check that and return a better version error?

**Comment by Pokem0n2** [comment]
many thanks!!! i uninstalled node.js v14.17.5, then installed node-v20.15.0-x64.msi (include npm 10.7.0 in itself) and nvm-setup.exe (v1.1.12)

PS C:\Users\Atnil> nvm use 20
Now using node v20.15.0 (64-bit)

PS C:\Users\Atnil> node -v
v20.15.0
PS C:\Users\Atnil> npm -v
10.7.0

there's a notice between "npm install" and "npm install -g @vue/cli"
--------------------------------------------------------------------------------
npm notice
npm notice New minor version of npm available! 10.7.0 -> 10.8.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.1
npm notice To update run: npm install -g npm@10.8.1
npm notice
--------------------------------------------------------------------------------
i ignored this and went on, and "npm run serve" worked this time.

thanks again for not only your help but also thy awesome work ! best wishes ! :-)

**Comment by pketh** [comment]
Thanks! Glad you figured it out :)
